steps:
  # Build the image using Dockerfile
  - id: "build image"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${COMMIT_SHA}", "."]

  # Push the built image to the container registry service
  - id: "push image to Container Registry"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${COMMIT_SHA}"]

  # Deploy containers to GKE
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
    - run 
    - --filename=k8s/deployment.yaml
    - --image=gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${COMMIT_SHA} 
    - --location=us-central1-c
    - --cluster=k8s-cluster

# Here are the substitution variables related to the services.
substitutions:
  _REGION: us-central1 # The region where the cloud services are located.
  _SERVICE_NAME: emd-csv-service # The name of the App Cloud Run service (Any name you choose).


# The structure of the built image
images:
  - gcr.io/${PROJECT_ID}/${_SERVICE_NAME}