apiVersion: apps/v1
kind: Deployment
metadata:
  name: emd-csv-deploy
spec:
  selector:
    matchLabels:
      app: emd-csv-app
  replicas: 1
  restartPolicy: Never
  template:
    metadata:
      labels:
        app: emd-csv-app
    spec:
      containers:
        - name: emd-csv-app
          image: gcr.io/gcp-training-386807/emd-csv-service

