apiVersion: batch/v1
kind: Job
metadata:
  name: emd-csv-job
spec:
  completions: 1
  template:
    metadata:
      name: emd-csv-pod
    spec:
      restartPolicy: Never
      containers:
        - name: emd-csv-app
          image: gcr.io/gcp-training-386807/emd-csv-service

